# Generated by Django 5.1 on 2025-09-27 04:40

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmpresaTercera',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre de la empresa externa', max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Etapa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
                ('orden_secuencia', models.PositiveIntegerField(default=0, help_text='Orden de la etapa en el flujo')),
            ],
            options={
                'ordering': ['orden_secuencia'],
            },
        ),
        migrations.CreateModel(
            name='LineaProducto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Orden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo_orden', models.CharField(editable=False, max_length=20, unique=True)),
                ('estado', models.CharField(choices=[('CARRITO', 'Carrito'), ('PROCESADA', 'Procesada'), ('EN_PRODUCCION', 'En Producción'), ('COMPLETADA', 'Completada')], default='CARRITO', max_length=20)),
                ('fecha_creacion', models.DateTimeField(auto_now_add=True)),
                ('lote_asignado', models.CharField(blank=True, help_text='Código de lote para la producción', max_length=50, null=True)),
                ('usuario', models.ForeignKey(help_text='Usuario que realiza el pedido', on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Proceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('orden_secuencia', models.PositiveIntegerField(default=0, help_text='Orden del proceso en la etapa')),
                ('etapa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='procesos', to='core.etapa')),
            ],
            options={
                'ordering': ['etapa__orden_secuencia', 'orden_secuencia'],
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('codigo', models.CharField(help_text='Código único del producto', max_length=50, unique=True)),
                ('presentacion', models.CharField(help_text='Ej: 20mg, 50ml, Caja x 100', max_length=100)),
                ('linea', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='productos', to='core.lineaproducto')),
            ],
        ),
        migrations.CreateModel(
            name='ItemOrden',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cantidad', models.PositiveIntegerField(default=1)),
                ('orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='core.orden')),
                ('producto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items_orden', to='core.producto')),
            ],
        ),
        migrations.CreateModel(
            name='SeguimientoProduccion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('estado', models.CharField(choices=[('PENDIENTE', 'Pendiente'), ('EN_PROGRESO', 'En Progreso'), ('PAUSADO', 'Pausado'), ('FINALIZADO', 'Finalizado')], default='PENDIENTE', max_length=20)),
                ('fecha_inicio', models.DateTimeField(blank=True, null=True)),
                ('fecha_fin', models.DateTimeField(blank=True, null=True)),
                ('duracion_total_segundos', models.BigIntegerField(default=0, help_text='Duración acumulada del trabajo en segundos')),
                ('item_orden', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='seguimientos', to='core.itemorden')),
            ],
        ),
        migrations.CreateModel(
            name='RegistroActividad',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_evento', models.CharField(choices=[('INICIO', 'Inicio'), ('PAUSA', 'Pausa'), ('REANUDAR', 'Reanudar'), ('FIN', 'Fin')], max_length=20)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('seguimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='actividades', to='core.seguimientoproduccion')),
            ],
        ),
        migrations.CreateModel(
            name='Subproceso',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=255)),
                ('orden_secuencia', models.PositiveIntegerField(default=0, help_text='Orden del subproceso en el proceso')),
                ('proceso', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='subprocesos', to='core.proceso')),
            ],
            options={
                'ordering': ['proceso__etapa__orden_secuencia', 'proceso__orden_secuencia', 'orden_secuencia'],
            },
        ),
        migrations.AddField(
            model_name='seguimientoproduccion',
            name='subproceso_actual',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='core.subproceso'),
        ),
        migrations.CreateModel(
            name='Trabajador',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombres', models.CharField(max_length=200)),
                ('apellidos', models.CharField(max_length=200)),
                ('codigo', models.CharField(blank=True, help_text='Código único del trabajador', max_length=50, null=True, unique=True)),
                ('tipo', models.CharField(choices=[('PLANILLA', 'Planilla'), ('TERCERO', 'Tercero')], default='PLANILLA', max_length=10)),
                ('empresa_tercera', models.ForeignKey(blank=True, help_text="Empresa si es de tipo 'Tercero'", null=True, on_delete=django.db.models.deletion.SET_NULL, to='core.empresatercera')),
            ],
        ),
        migrations.AddField(
            model_name='seguimientoproduccion',
            name='trabajadores_asignados',
            field=models.ManyToManyField(blank=True, to='core.trabajador'),
        ),
        migrations.CreateModel(
            name='RegistroAsistencia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=django.utils.timezone.now)),
                ('asistio', models.BooleanField(default=True)),
                ('seguimiento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.seguimientoproduccion')),
                ('trabajador', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.trabajador')),
            ],
            options={
                'unique_together': {('seguimiento', 'trabajador', 'fecha')},
            },
        ),
    ]
